### ISSUE TITLE
firewalld restart/reload needed

### ISSUE THREAD

**Issue by joba12** [marcelnijenhof/ansible-role-firewalld#5]
After running your example playbook the http service is not enabled.

TASK [marcelnijenhof.firewalld : Add firewalld rules for services from vars] ***
changed: [localhost] => (item={u'service': u'http'})

public (default, active)
  interfaces: ens192
  sources:
  services: dhcpv6-client ssh
  ports:
  masquerade: no
  forward-ports:
  icmp-blocks:
  rich rules:

Run the playbook again:
TASK [marcelnijenhof.firewalld : Add firewalld rules for services from vars] ***
ok: [localhost] => (item={u'service': u'http'})

But we still need to reload firewalld.

After reload:
public (default, active)
  interfaces: ens192
  sources:
  services: dhcpv6-client http ssh
  ports:
  masquerade: no
  forward-ports:
  icmp-blocks:
  rich rules:

Bug or Feature?

**Comment by marcelnijenhof** [comment]
There was a small change in the hook code by gibbsoft.
Unfortunately that introduced a bug.

This bug is solved by:
  https://github.com/marcelnijenhof/ansible-role-firewalld/commit/5fdc706a3d4ca8b8b705081503e9f8b0f534411c

**Comment by joba12** [comment]
It works, thank you!
